---
- name: copy archive playbook
  hosts: webnodes      # Inventory hosts group / server to act on
  become_method: sudo       # Set become method
  remote_user: web        # Update username for remote server
  tasks:
    - name : copy tomcat archive
      copy:
        src: /home/acm/ansible/apache-tomcat-10.0.6.tar.gz
        dest: /home/web/
        force: yes
    - name : copy java archive
      copy:
        src: /home/acm/ansible/jdk-11.0.11_linux-x64_bin.tar.gz
        dest: /home/web/
        force: yes
    - name : copy jre
      copy:
        src: /home/acm/ansible/jre-8u291-linux-x64.tar.gz
        dest: /home/web/
        force: yes
    - name : setup jre
      command : 'tar zxvf jre-8u291-linux-x64.tar.gz'