---
- name: Java playbook
  hosts: all       # Inventory hosts group / server to act on
  become: yes               # If to escalate privilege
  become_method: sudo       # Set become method
  remote_user: web        # Update username for remote server
  vars:
    java_archive_location: /home/web
    java_name: "{{java_archive_location}}/jdk11.0.11"
    java_archive: "{{java_archive_location}}/jdk-11.0.11_linux-x64_bin.tar.gz"
  
  - name: Unpack archive
    command: "tar -zxf {{java_archive}} -C {{java_archive_location}} creates={{java_name}}"

  - name: Fix ownershipyml
    file: state=directory path={{java_name}} owner=root group=root recurse=yes

  - name: Make Java available for system
    command: 'alternatives --install "/usr/bin/java" "java" "{{java_name}}/bin/java" 2000'